---
functional:
  - Сайт должен быть удобным на мобильном устройстве
  - Пользователь должен иметь возможность зарегистрироваться на сайте 
  - Пользователь должен иметь возможность авторизовываться к ранее созданном аккаунте
  - Пользователь должен иметь возможность редактировать свой аккаунт (профиль)
  - Пользователь должен иметь возможность создавать игры
non-functional:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Сайт должен иметь адаптивную верстку
  - Управление игрой должно быть интуитивно понятным и легко осуществляемым
  - Игра должна иметь различные уровни сложности, чтобы пользователь мог выбрать подходящий для себя уровень
